apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: docs-route
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: "132.226.43.62"
spec:
  parentRefs:
  - name: docs-gateway
    sectionName: websecure
  hostnames:
  - "k3s.sudhanva.me"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: docs
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: docs-redirect
  namespace: default
spec:
  parentRefs:
  - name: docs-gateway
    sectionName: web
  hostnames:
  - "k3s.sudhanva.me"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-tls
  namespace: default
spec:
  secretName: docs-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  commonName: "k3s.sudhanva.me"
  dnsNames:
  - "k3s.sudhanva.me"
